### ISSUE TITLE
What is the backup plan? 

### ISSUE THREAD

**Issue by Brli** [heikkiket/gallery#1]
If you just corrupted the image during an edition, and it just spread out with instant sync?

**Comment by heikkiket** [comment]
Thanks a lot for creating an issue!

This is my first public free software project, and it really made me happy to notice that someone cares enough about this project to create an issue. 

I'd imagine there are three ways to address this kind of situation.
 1) Synchronization tool has versioning in it
 2) Separate backup system versions all the files
 3) Image editing software offers backup functionality

I's say options 1) and 2) sound most reasonable for me. The idea of this gallery is just to put files into directories, so also backups should be then done in file/filesystem level.

Now, interesting question is also how to handle metadata changes in gallery.toml. I have sometimes wondered if this metadata should be versioned somehow with this tooling. That would increase the complexity of this project a lot. Also I want this to be easily hackable by anyone, with any tool out there. Offering easily hackable versioning would be a big challenge. 

If this project really turns into a realistic photo management solution I think we should then consider certain "happy paths" and integrations with popular tools. For example many users would probably sync their photo collection with Nextcloud or Syncthing, and then backing up or versioning should be considered together with those tools.

Also, separately backing up or versioning this photo collection could be done with for example Duplicity or maybe even with Git. Offering easy integration or triggering backups automatically when contents change would be a cool feature.
